slam_toolbox:
  ros__parameters:
    use_sim_time: !!bool true
    mode: !!str mapping
    odom_frame: !!str odom
    map_frame: !!str map
    base_frame: !!str base_footprint
    scan_topic: !!str /scan
    map_update_interval: !!float 2.0
    resolution: !!float 0.05
    max_laser_range: !!float 12.0
    minimum_time_interval: !!float 0.1
    transform_publish_period: !!float 0.05
    transform_timeout: !!float 0.2
    tf_buffer_duration: !!float 30.0
    stack_size_to_use: !!int 40000000
    enable_interactive_mode: !!bool true
