twist_mux:
  ros__parameters:
    use_sim_time: !!bool true
    topics:
      navigation:
        topic: /cmd_vel_nav
        timeout: !!float 0.5
        priority: !!int 50
      teleop:
        topic: /cmd_vel_teleop
        timeout: !!float 0.5
        priority: !!int 100
    locks:
      estop:
        topic: /cmd_vel_lock
        timeout: !!float 0.0
        priority: !!int 255
