controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
    joints:
      - left_wheel_joint
      - right_wheel_joint
    interfaces:
      - position
      - velocity

diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - left_wheel_joint
    right_wheel_names:
      - right_wheel_joint

    wheel_separation: 0.54
    wheel_radius: 0.095

    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    open_loop: false
    position_feedback: true

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.8
    linear.x.min_velocity: -0.4
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.8

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.8
    angular.z.min_velocity: -1.8
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 2.5

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: base_imu
    frame_id: imu_link
