- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/scan"
  gz_topic_name: "/world/sentinel_warehouse/model/nexus_sentinel/link/laser_link/sensor/front_lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/imu"
  gz_topic_name: "/world/sentinel_warehouse/model/nexus_sentinel/link/imu_link/sensor/base_imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/camera/image"
  gz_topic_name: "/world/sentinel_warehouse/model/nexus_sentinel/link/camera_link/sensor/front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/world/sentinel_warehouse/model/nexus_sentinel/link/camera_link/sensor/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
